config/routes.rb
Rails.application.routes.draw do
  get "/", to: "home#top"
  get "about", to: "home#about"

  get "password/reset", to: "password_resets#new", as: 'new_password_reset'
  post "password/create", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  post "password/reset", to: "password_resets#update"
  patch "password/reset", to: "password_resets#update"
  post "password/reset/edit", to: "password_resets#update"
  patch "password/reset/edit", to: "password_resets#update"

  post "users/:id/update", to: "users#update"
  patch "users/:id/update", to: "users#update"
  get "users/:id/edit", to: "users#edit"
  get "signup", to: "users#new"
  post "users/create", to: "users#create"
  get "users/index", to: "users#index"
  get "users/:id", to: "users#show"
  post "login", to: "users#login"
  post "logout", to: "users#logout"
  get "login", to: "users#login_form"
  get "users/:id/likes", to: "users#likes"
  delete "users/:id", to: 'users#destroy', as: 'delete_user'

  get "posts/index", to: "posts#index"
  get "posts/new", to: "posts#new"
  get "posts/:id", to: "posts#show"
  post "posts/create", to: "posts#create"
  get "posts/:id/edit", to: "posts#edit"
  post "posts/:id/update", to: "posts#update"
  patch "posts/:id/update", to: "posts#update"
  post "posts/:id/destroy", to: "posts#destroy"

  get "maps/index", to: "maps#index"
  get "maps/new", to: "maps#new"
  get "maps/:id", to: "maps#show"
  post "maps/create", to: "maps#create"
  get "maps/:id/edit", to: "maps#edit"
  post "maps/:id/update", to: "maps#update"
  patch "maps/:id/update", to: "maps#update"
  post "maps/:id/destroy", to: "maps#destroy"

  post "likes/:post_id/create", to: "likes#create"
  post "likes/:post_id/destroy", to: "likes#destroy"

  get "term", to: "home#term"
  get "privacy", to: "home#privacy"
  get "cookie", to: "home#cookie"
  get "rule", to: "home#rule"

  get "contacts/new", to: "contacts#new"
  post "contacts/create", to: "contacts#create"

  # ネストさせる
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  	get "followings" => "relationships#followings", as: "followings"
  	get "followers" => "relationships#followers", as: "followers"
  end

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  rescue_from ActiveSupport::MessageVerifier::InvalidSignature, with: :invalid_signature

  def new

  end

  def create
    @user = User.find_by(email: params[:email])

    if @user.present?
      begin
        # メールを送る
        PasswordResetMailer.reset(@user).deliver_later
        flash[:success] = "リクエストありがとうございます。パスワードリセットメールを送りました。"
        redirect_to '/'
      rescue => e
        # メール送信に失敗した場合の処理
        Rails.logger.error("Failed to send password reset email: #{e.message}")
        flash[:danger] = "メール送信に失敗しました。しばらくしてから再度お試しください。"
        render :new
      end
    else
      flash[:danger] = "メールアドレスを見つかりませんでした。ご確認お願いします。"
      render :new
    end
  end

  def edit
    @user = User.find_signed!(params[:token], purpose: "password_reset")
  end

  def update
    @user = User.find_signed!(params[:token], purpose: "password_reset")
    if @user.update(password_params)
      flash[:success] = "パスワードがリセットされました。ログインしてください。"
      redirect_to '/login'
    else
      render :edit
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def invalid_signature
    flash[:danger] = "URLの有効期限が切れています。もう一度リクエストお願いします。"
    redirect_to new_password_reset_path
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]), local: true do |form| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
      <% @user.errors.full_messages.each do |message| %>
        <div>
          <%= message %>
        </div>
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control mb-3" %>
  </div>
  <div class="form-group">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "form-control mb-3" %>
  </div>
  <%= form.hidden_field :token, value: params[:token] %>
  <%= form.submit 'パスワードをリセットする', class: "btn btn-primary" %>
<% end %>

app/views/password_resets/new.html.erb
<div class="container">
  <h3 class="contents-title">パスワードリセット申請</h3>
  <div class="form">
    <div class="form-body">
      <%= form_with url:"/password/create",  local: true do |form| %>
        <div class="contact-form">
          <%= form.label "E-mail" %>
          <%= form.text_field :email, placeholder: "user@example.com" %>
          <%= form.submit '申請' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="go-home">
  <%= link_to("<ページの上へ戻る>", "#top") %>
</div>