config/routes.rb
Rails.application.routes.draw do
  get "/", to: "home#top"
  get "about", to: "home#about"

  get "password/reset", to: "password_resets#new", as: 'new_password_reset'
  post "password/create", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  post "password/reset", to: "password_resets#update"
  patch "password/reset", to: "password_resets#update"
  post "password/reset/edit", to: "password_resets#update"
  patch "password/reset/edit", to: "password_resets#update"

  post "users/:id/update", to: "users#update"
  patch "users/:id/update", to: "users#update"
  get "users/:id/edit", to: "users#edit"
  get "signup", to: "users#new"
  post "users/create", to: "users#create"
  get "users/index", to: "users#index"
  get "users/:id", to: "users#show"
  post "login", to: "users#login"
  post "logout", to: "users#logout"
  get "login", to: "users#login_form"
  get "users/:id/likes", to: "users#likes"
  delete "users/:id", to: 'users#destroy', as: 'delete_user'

  get "posts/index", to: "posts#index"
  get "posts/new", to: "posts#new"
  get "posts/:id", to: "posts#show"
  post "posts/create", to: "posts#create"
  get "posts/:id/edit", to: "posts#edit"
  post "posts/:id/update", to: "posts#update"
  patch "posts/:id/update", to: "posts#update"
  post "posts/:id/destroy", to: "posts#destroy"

  get "maps/index", to: "maps#index"
  get "maps/new", to: "maps#new"
  get "maps/:id", to: "maps#show"
  post "maps/create", to: "maps#create"
  get "maps/:id/edit", to: "maps#edit"
  post "maps/:id/update", to: "maps#update"
  patch "maps/:id/update", to: "maps#update"
  post "maps/:id/destroy", to: "maps#destroy"

  post "likes/:post_id/create", to: "likes#create"
  post "likes/:post_id/destroy", to: "likes#destroy"

  get "term", to: "home#term"
  get "privacy", to: "home#privacy"
  get "cookie", to: "home#cookie"
  get "rule", to: "home#rule"

  get "contacts/new", to: "contacts#new"
  post "contacts/create", to: "contacts#create"

  # ネストさせる
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  	get "followings" => "relationships#followings", as: "followings"
  	get "followers" => "relationships#followers", as: "followers"
  end

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, {presence: true}
  validates :email, {presence: true, uniqueness: true}
  validates :image, {presence: true}
  has_many :posts, dependent: :destroy
  has_secure_password
  mount_uploader :image, ImageUploader

  def posts
    return Post.where(user_id: self.id)
  end

  def maps
    return Map.where(user_id: self.id)
  end

  def likes
    return Like.where(user_id: self.id)
  end

  # フォローしている関連付け
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy

  # フォローされている関連付け
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # フォローしているユーザーを取得
  has_many :followings, through: :active_relationships, source: :followed

  # フォロワーを取得
  has_many :followers, through: :passive_relationships, source: :follower

  # 指定したユーザーをフォローする
  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  # 指定したユーザーのフォローを解除する
  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  # 指定したユーザーをフォローしているかどうかを判定
  def following?(user)
    followings.include?(user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #ログイン中のユーザーが出来る事
  before_action :authenticate_user, {only: [:index, :show, :edit, :update]}
  #ログイン中のユーザーが出来ない事
  before_action :forbid_login_user, {only: [:new, :create, :login_form, :login]}
  #ログインiDとユーザーidが等しい時に出来る事
  before_action :ensure_correct_user, {only: [:edit, :update]}
  require 'mini_magick'

  def index
    @users = User.all.order(created_at: :asc)
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "ユーザー登録が完了しました"
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    @user.update(user_params)

    if @user.save
      flash[:notice] = "ユーザー情報を編集しました"
      redirect_to("/users/#{@user.id}")
    else
      render("users/edit")
    end
  end

  def destroy
    @user = User.find_by(id: params[:id])
    if @user
      @user.destroy
      flash[:notice] = "退会しました"
    else
      flash[:alert] = "ユーザーが見つかりませんでした"
    end
    redirect_to "/"
  end

  def login_form
  end

  def login
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "ログインしました"
      redirect_to("/posts/index")
    else
      @error_message = "メールアドレスまたはパスワードが間違っています"
      @email = params[:email]
      @password = params[:password]
      render("users/login_form")
    end
  end

  def logout
    session[:user_id] = nil
    flash[:notice] = "ログアウトしました"
    redirect_to("/")
  end

  def likes
    @user = User.find_by(id: params[:id])
    @likes = Like.where(user_id: @user.id)
  end

  def ensure_correct_user
    if @current_user.id != params[:id].to_i
      flash[:notice] = "権限がありません"
      redirect_to("/posts/index")
    end
  end

  private
    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :image, :password, :profile, :youtube, :twitter, :instagram)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% content_for :title do %>
  ユーザー編集
<% end %>

<% breadcrumb :users_edit %>
<div class="container">
  <h3 class="contents-title">ユーザー編集</h3>
  <div class="form">
    <div class="form-body">
      <% @user.errors.full_messages.each do |message| %>
        <div class="form-error">
          <%= message %>
        </div>
      <% end %>
      <%= form_with model: @user, url: "/users/#{@user.id}/update", local: true do |form| %>
        <%= form.label "ユーザー名" %>
        <%= form.text_field :name, value: @user.name %>
        <%= form.label "メールアドレス" %>
        <%= form.email_field :email, value: @user.email %>
        <%= form.label "プロフィール画像" %>
        <%= form.file_field :image, value: @user.image %>
        <%= form.label "プロフィール" %>
        <%= form.text_field :profile, value: @user.profile %>
        <%= form.label "YouTube" %>
        <%= form.text_field :youtube, value: @user.youtube %>
        <%= form.label "Twitter" %>
        <%= form.text_field :twitter, value: @user.twitter %>
        <%= form.label "Instagram" %>
        <%= form.text_field :instagram, value: @user.instagram %>
        <%= form.submit "登録" %>
      <% end %>
    </div>
  </div>
</div>

<div class="go-home">
  <%= link_to("<ページの上へ戻る>", "#top") %>
</div>

app/views/users/index.html.erb
<% content_for :title do %>
  ユーザー一覧
<% end %>

<% breadcrumb :users %>
<div class="container">
  <h3 class="contents-title">ユーザー一覧</h3>
  <div class="users-index">
    <% @users.each do |user| %>
      <div class="users-index-item">
        <div class="user-left">
          <%= image_tag user.image.url, alt: "ユーザー画像" %>
        </div>
        <div class="user-right">
          <%= link_to(user.name, "/users/#{user.id}") %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="go-home">
  <%= link_to("<ページの上へ戻る>", "#top") %>
</div>

app/views/users/likes.html.erb
<div class="container">
  <div class="user">
    <%= image_tag("/user_images/#{@user.image}"), alt: "ユーザー画像"  %>
    <h2><%= @user.name %></h2>
    <p><%= @user.email %></p>
    <% if @user.id == @current_user.id %>
      <%= link_to("編集", "/users/#{@user.id}/edit") %>
    <% end %>
  </div>
  
  <ul class="user-tabs">
    <li><%= link_to("投稿", "/users/#{@user.id}") %></li>
    <li class="active"><%= link_to("いいね!", "/users/#{@user.id}/likes") %></li>
  </ul>

  <% @likes.each do |like| %>
    <% post = Post.find_by(id: like.post_id) %>
    
    <div class="posts-index-item">
      <div class="post-left">
        <%= image_tag("/user_images/#{post.user.image}"), alt: "投稿された釣果画像（単枚）" %>
      </div>
      <div class="post-right">
        <div class="post-user-name">
          <%= link_to(post.user.name, "/users/#{post.user.id}") %>
        </div>
        <%= link_to(post.content, "/posts/#{post.id}") %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/login_form.html.erb
<% content_for :title do %>
  ログイン
<% end %>

<% breadcrumb :login %>
<div class="container">
  <h3 class="contents-title">ログイン</h3>
    <div class="form">
      <div class="form-body">
        <% if @error_message %>
          <div class="form-error">
            <%= @error_message %>
          </div>
        <% end %>
        <%= form_with  url: "/login", local: true do |form| %>
          <%= form.label "メールアドレス" %>
          <%= form.email_field :email, value: @email  %>
          <%= form.label "パスワード" %>
          <%= form.password_field :password, value: @password %>
          <%= link_to("☞新規登録はこちらから", "/signup") %>
          <%= link_to "パスワードを忘れた?",password_reset_path, class: 'link-secondary d-inline-block ms-3' %>
          <%= form.submit "ログイン" %>
        <% end %>
      </div>
    </div>
</div>

<div class="go-home">
  <%= link_to("<ページの上へ戻る>", "#top") %>
</div>

app/views/users/new.html.erb
<% content_for :title do %>
  新規ユーザー登録
<% end %>

<% breadcrumb :singup %>
<div class="container">
<h3 class="contents-title">新規登録</h3>
  <div class="form">
    <div class="form-body">
      <p style='color: red'>※釣果を投稿するには新規ユーザー登録が必要です！！<p>
      <br>
      <% @user.errors.full_messages.each do |message| %>
        <div class="form-error">
          <%= message %>
        </div>
      <% end %>
      <%= form_with model: @user, url: "/users/create", local: true do |form| %>
        <%= form.label "ユーザー名" %><span> ※10文字以内</span>
        <%= form.text_field :name, size: 10 %>
        <%= form.label "メールアドレス" %>
        <%= form.email_field :email %>
        <%= form.label "パスワード" %>
        <%= form.password_field :password %>
        <%= form.label "プロフィール画像" %>
        <%= form.file_field :image %>
        <%= form.label "プロフィール" %><span> ※30文字以内</span>
        <%= form.text_field :profile, size: 30 %>
        <%= link_to("☞ログインはこちらから", "/login") %>
        <%= form.submit "新規登録" %>
      <% end %>
    </div>
  </div>
</div>

<div class="go-home">
  <%= link_to("<ページの上へ戻る>", "#top") %>
</div>

app/views/users/show.html.erb
<% content_for :title do %>
  ユーザー情報
<% end %>

<% breadcrumb :users_show %>
<div class="contents">
  <h3 class="contents-title">ユーザー情報</h3>
  <div class="user">
    <%= image_tag @user.image.url, alt: "ユーザー画像" %>
    <h2><%= @user.name %><span> さん</span></h2>
    <% if @user.id == @current_user.id %>
      <p><%= @user.email %></p>
    <% end %>
    <p><%= @user.profile %></p>

    <ul class="profile-links">
      <% if @user.youtube.present? %>
        <li class="profile-link">
          <%= link_to @user.youtube, target: :_blank do %>
            <i class="fab fa-youtube fa-2x"></i>
          <% end %>
        </li>
      <% end %>
      <% if @user.twitter.present? %>
        <li class="profile-link">
          <%= link_to @user.twitter, target: :_blank do %>
            <i class="fab fa-twitter fa-2x"></i>
          <% end %>
        </li>
      <% end %>
      <% if @user.instagram.present? %>
        <li class="profile-link">
          <%= link_to @user.instagram, target: :_blank do %>
            <i class="fab fa-instagram fa-2x"></i>
          <% end %>
        </li>
      <% end %>
    </ul>

    <% if @user.id == @current_user.id %>
      <div class="user-edit">
        <%= link_to("編集する", "/users/#{@user.id}/edit") %>
        <script>
          function confirmDelete(userId) {
            if (confirm('本当にこのユーザーを削除しますか？')) {
              window.location.href = '/users/' + userId;
            }
          }
        </script>
        <%= link_to '退会する', user_path(@user), method: :delete, data: { confirm: '本当に退会しますか？' } %>
      </div>
    <% end %>
    <% if @current_user != @user %>
      <% if @current_user.following?(@user) %>
        <%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete %>
      <% else %>
        <%= link_to "フォローする", user_relationships_path(@user.id), method: :post %>
      <% end %>
    <% end %>

    <span>フォロー中</span><%= link_to @user.followings.count, user_followings_path(@user)%>
    <span>フォロワー</span><%= link_to @user.followers.count, user_followers_path(@user) %>
  </div>

  <h3 class="contents-title">釣果一覧</h3>

  <div class="posts-contents">
    <% @user.posts.each do |post| %>
      <div class="posts-item">
        <div class="user-post-datetime">
          <span>投稿日：</span>
          <%= post.created_at.strftime("%Y-%m-%d %H:%M") %>
        </div>

        <div class="top-user-image">
          <% if post.images.length < 2 %>
            <% post.images.each do |image| %>
              <%= image_tag image.to_s, class: "post-img", alt: "投稿された釣果画像（単枚）" %>
            <% end %>
          <% else %>
            <div class="swiper">
              <div class= "swiper-wrapper ">
                <% post.images.each do |image| %>
                  <%= image_tag image.to_s, class: "swiper-slide index-img", alt: "投稿された釣果画像（複数枚）" %>
                <% end %>
              </div>
              <div class="swiper-button-prev"></div>
              <div class="swiper-button-next"></div>
              <div class="swiper-pagination"></div>
            </div>
          <% end %>
        </div>

        <div class="posts-index-right">
          <%= link_to("👉釣果詳細","/posts/#{post.id}") %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<% if @current_user && @posts or @post or @user %>
  <p id="page-top"><%= link_to("釣果を投稿する","/posts/new") %></p>
<% end %>

<% if @current_user == nil %>
  <p id="page-top"><%= link_to("新規登録する","/signup") %></p>
<% end %>

<div class="go-home">
  <%= link_to("<ユーザ一覧に戻る>","/users/index") %>
</div>